Credit = read.csv(file="~/Documents/TransactionSearchResults880.csv",head=TRUE)
Credit.1 <- subset(Credit,Credit$X.!="*")
Credit.1$Amount.1 <- abs(Credit.1$Amount) 
Credit.3 <- data.frame(aggregate(Amount.1~Item+Created.From,data=Credit.1,sum))
Credit.4 <- subset(Credit.3,Credit.3$Amount.1>0)
write.csv(Credit.4,file="~/Documents/Credit.csv",row.names=FALSE)
Credit.5=read.csv(file="~/Documents/Credit.csv",head=TRUE)
Credit.6 <- data.frame(aggregate(Amount.1~Catergory,data=Credit.5,sum))
write.csv(Credit.6,file="~/Documents/Creditv1.csv",row.names=FALSE)
